function [fitresult, gof] = TryFixFits(xxx, yyy)
%CREATEFITS(XXX,YYY)
%  Create fits.
%
%  Data for 'rat02' fit:
%      X Input : xxx
%      Y Output: yyy
%  Data for 'poly3' fit:
%      X Input : xxx
%      Y Output: yyy
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Nov-2015 11:34:00

%% Initialization.
ylimsPfix=[0,1];
ylimsres=[-0.1,0.1];
% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'rat02'.
[xData, yData] = prepareCurveData( xxx, yyy );

% Set up fittype and options.
ft = fittype( 'rat02' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.833500595588975 0.768854252429615 0.167253545494722];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'PfixAgainstPfILS' );

% Plot fit with data.
subplot( 2, 2, 1 );
h = plot( fitresult{1}, xData, yData );
legend( h, 'yyy vs. xxx', 'rat02', 'Location', 'NorthEast' );
title('rat02');
% Label axes
xlabel ('P_f_,_I_L_S');
ylabel ('P_f_i_x');
ylim(ylimsPfix);
grid on

% Plot residuals.
subplot( 2, 2, 3 );
h = plot( fitresult{1}, xData, yData, 'residuals' );
legend( h, 'rat02 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel ('P_f_,_I_L_S');
% ylabel ('');
ylim(ylimsres);

grid on

%% Fit: 'poly3'.
[xData, yData] = prepareCurveData( xxx, yyy );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Create a figure for the plots.
% figure( 'Name', 'poly3' );

% Plot fit with data.
subplot( 2, 2, 2 );
h = plot( fitresult{2}, xData, yData );
legend( h, 'yyy vs. xxx', 'poly3', 'Location', 'NorthEast' );
title('Poly3');
% Label axes
xlabel ('P_f_,_I_L_S');
ylabel ('P_f_i_x');
ylim(ylimsPfix);

grid on

% Plot residuals.
subplot( 2, 2, 4 );
h = plot( fitresult{2}, xData, yData, 'residuals' );
legend( h, 'poly3 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel ('P_f_,_I_L_S');
ylim(ylimsres);

grid on


